dist: bionic
sudo: false
language: python
env:
- TOXENV=flake8
- TOXENV=isort
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=py36-1.11-drf3.8
  - python: 3.6
    env: TOXENV=py36-1.11-drf3.9
  - python: 3.6
    env: TOXENV=py36-1.11-drf3.10
  - python: 3.6
    env: TOXENV=py36-1.11-drf3.11
  - python: 3.6
    env: TOXENV=py36-2.0-drf3.8
  - python: 3.6
    env: TOXENV=py36-2.0-drf3.9
  - python: 3.6
    env: TOXENV=py36-2.0-drf3.10
  - python: 3.6
    env: TOXENV=py36-2.0-drf3.11
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.8
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.9
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.10
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.11
  - python: 3.6
    env: TOXENV=py36-2.2-drf3.10
  - python: 3.6
    env: TOXENV=py36-2.2-drf3.11
  - python: 3.6
    env: TOXENV=py36-2.2-drf3.12
  - python: 3.6
    env: TOXENV=py36-3.0-drf3.11
  - python: 3.6
    env: TOXENV=py36-3.0-drf3.12
  - python: 3.6
    env: TOXENV=py36-3.1-drf3.11
  - python: 3.6
    env: TOXENV=py36-3.1-drf3.12
  - python: 3.6
    env: TOXENV=py36-3.2-drf3.11
  - python: 3.6
    env: TOXENV=py36-3.2-drf3.12
  - python: 3.7
    env: TOXENV=py37-1.11-drf3.8
  - python: 3.7
    env: TOXENV=py37-1.11-drf3.9
  - python: 3.7
    env: TOXENV=py37-1.11-drf3.10
  - python: 3.7
    env: TOXENV=py37-1.11-drf3.11
  - python: 3.7
    env: TOXENV=py37-2.0-drf3.8
  - python: 3.7
    env: TOXENV=py37-2.0-drf3.9
  - python: 3.7
    env: TOXENV=py37-2.0-drf3.10
  - python: 3.7
    env: TOXENV=py37-2.0-drf3.11
  - python: 3.7
    env: TOXENV=py37-2.1-drf3.8
  - python: 3.7
    env: TOXENV=py37-2.1-drf3.9
  - python: 3.7
    env: TOXENV=py37-2.1-drf3.10
  - python: 3.7
    env: TOXENV=py37-2.1-drf3.11
  - python: 3.7
    env: TOXENV=py37-2.2-drf3.10
  - python: 3.7
    env: TOXENV=py37-2.2-drf3.11
  - python: 3.7
    env: TOXENV=py37-2.2-drf3.12
  - python: 3.7
    env: TOXENV=py37-3.0-drf3.11
  - python: 3.7
    env: TOXENV=py37-3.0-drf3.12
  - python: 3.7
    env: TOXENV=py37-3.1-drf3.11
  - python: 3.7
    env: TOXENV=py37-3.1-drf3.12
  - python: 3.7
    env: TOXENV=py37-3.2-drf3.11
  - python: 3.7
    env: TOXENV=py37-3.2-drf3.12
  - python: 3.8
    env: TOXENV=py38-2.2-drf3.10
  - python: 3.8
    env: TOXENV=py38-2.2-drf3.11
  - python: 3.8
    env: TOXENV=py38-2.2-drf3.12
  - python: 3.8
    env: TOXENV=py38-3.0-drf3.11
  - python: 3.8
    env: TOXENV=py38-3.0-drf3.12
  - python: 3.8
    env: TOXENV=py38-3.1-drf3.11
  - python: 3.8
    env: TOXENV=py38-3.1-drf3.12
  - python: 3.8
    env: TOXENV=py38-3.2-drf3.11
  - python: 3.8
    env: TOXENV=py38-3.2-drf3.12
  - python: 3.9
    env: TOXENV=py39-2.2-drf3.10
  - python: 3.9
    env: TOXENV=py39-2.2-drf3.11
  - python: 3.9
    env: TOXENV=py39-2.2-drf3.12
  - python: 3.9
    env: TOXENV=py39-3.0-drf3.11
  - python: 3.9
    env: TOXENV=py39-3.0-drf3.12
  - python: 3.9
    env: TOXENV=py39-3.1-drf3.11
  - python: 3.9
    env: TOXENV=py39-3.1-drf3.12
  - python: 3.9
    env: TOXENV=py39-3.2-drf3.11
  - python: 3.9
    env: TOXENV=py39-3.2-drf3.12

install:
- pip install tox coveralls
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
