[envs.default]
dependencies = [
    "coverage[toml]",
    "factory-boy",
    "jsonmask",
]

[envs.style]
detached = true
dependencies = [
  "flake8",
  "isort",
]
[envs.style.scripts]
check = [
  "flake8 .",
  "isort --check-only --diff .",
]
fmt = [
  "isort .",
  "check",
]

[envs.test.scripts]
test = [
    "coverage run -m django test -v2 --settings=tests.settings",
    "coverage report",
]

[envs.test.overrides]
matrix.django.dependencies = [
    { value = "django>=2.2,<3.0", if = ["2.2"] },
    { value = "django>=2.0,<3.1", if = ["3.0"] },
    { value = "django>=2.1,<3.2", if = ["3.1"] },
    { value = "django>=2.2,<4.0", if = ["3.2"] },
    { value = "django>=4.0,<4.1", if = ["4.0"] },
]
matrix.drf.dependencies = [
    { value = "djangorestframework>=3.10,<3.11", if = ["3.10"] },
    { value = "djangorestframework>=3.11,<3.12", if = ["3.11"] },
    { value = "djangorestframework>=3.12,<3.13", if = ["3.12"] },
    { value = "djangorestframework>=3.13,<3.14", if = ["3.13"] },
]

[[envs.test.matrix]]
python = ["3.7", "3.8", "3.9"]
django = ["2.2"]
drf = ["3.10", "3.11", "3.12", "3.13"]

[[envs.test.matrix]]
python = ["3.7", "3.8", "3.9"]
django = ["3.0", "3.1", "3.2"]
drf = ["3.11", "3.12", "3.13"]

[[envs.test.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]
django = ["4.0", "4.1", "4.2"]
drf = ["3.11", "3.12", "3.13"]

[[envs.test.matrix]]
python = ["3.10"]
django = ["3.2", "4.0", "4.1", "4.2"]

[[envs.test.matrix]]
python = ["3.11"]
django = ["4.1", "4.2"]
